### ISSUE TITLE
Warning about ESP_CAM_CONFIG.json file

### ISSUE THREAD

**Issue by SargonofAssyria** [Hoeby/ESP32-Doorbell#12]
After updated the new firmware.bin and the 2 changed html files I get this warning:
[W] 01/13 09:19:55 !! Config key quality doesn't exist in ESP_CAM_CONFIG.json!!

I also noticed that after an update the cam and a reboot does not initialize any more, power has to be unplugged to get the cam initialized again.

**Comment by jvanderzande** [comment]
The warning is correct as it indeed is missing the first time the config is loaded, hence the warning, but I had no problem after that.
Can change the CAM setting fine and a reboot doesn't show the warning anymore.
Can you still replicate the issue and if so, give me the exact steps to take to get the issue you see?

**Comment by SargonofAssyria** [comment]
No it was a one time only warning, but it might be confusing for others.

**Comment by jvanderzande** [comment]
This is by design as we need to check and inform people, when they restore an older config file, of missing items. In this case the software was updated so it will warn about it the first time and one should go into the setup window of either the CAM or ESP settings when a warning is received, to check the setting and save it.
